import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Saidbar from "./_Components/Saidbar";
import Navbar from "./_Components/Navbar";
// import localFont from "next/font/local";

// const MyFOnt = localFont({
//   src: "/public/fonts/NeueMachina-Ultrabold.otf",
//   display: "swap",
// });

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="w-[1535.3] mx-auto h-screen overflow-hidden">
          <Navbar />
          <div className="flex">
            <Saidbar />
            <div className="w-full">{children}</div>
          </div>
        </div>
      </body>
    </html>
  );
}
